routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')
    ->group(function () {

        Auth::routes();

        Route::namespace('Admin')
            ->middleware(['auth'])
            ->name('admin.')
            ->group(function () {

                // Route Home
                Route::get('home', 'HomeController@index')->name('index');

                // Route Designer
                Route::resource('designer', 'DesignerController');

                // Route Email
                Route::resource('email', 'EmailController');
                Route::get('email/invite/{email}', 'EmailController@invite')->name('email.invite');

                // Route Link
                Route::get('links', 'LinkController@index')->name('link.index');

                // Route User Register
                Route::get('user_register', 'UserRegisterController@index')->name('userRegister.index');
            });
    });

// Register
Route::get('designers/find', 'DesignerController@find')->name('designer.find');
Route::get('register/{url}', 'RegisterInviteController@register')->name('register.invite');
Route::post('register/store/{link}', 'RegisterInviteController@store')->name('register.invite.store');

// Home
Route::get('', 'HomeController@index')->name('index');

app/Models/Link.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    public $timestamps = true;
    protected $fillable = ['status_id', 'email_id', 'url', 'code'];

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    public function status()
    {
        return $this->belongsTo(StatusLink::class);
    }

    public function email()
    {
        return $this->belongsTo(Email::class);
    }
    
    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */
    
    /*
    |--------------------------------------------------------------------------
    | ACCESORS
    |--------------------------------------------------------------------------
    */
    
    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
}

app/Http/Controllers/Admin/LinkController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Link;
use DataTables;
use Illuminate\Http\Request;

/**
 * Class LinkController
 *
 * @package App\Http\Controllers\Admin
 */
class LinkController extends Controller
{    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Link::query();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('status', function($row) {
                    return $row->status->status_label;
                })
                ->addColumn('email', function($row) {
                    return $row->email->email;
                })
                ->rawColumns(['status'])
                ->make(true);
        }
        
        return view('admin.pages.link.index');
    }
}

resources/views/admin/pages/link/index.blade.php
@extends('admin.layouts.template')
@section('pageTitle', 'Link')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover" id="link-table">
                            <thead>
                            <tr>
                                <th>Status</th>
                                <th>Email</th>
                                <th>URL</th>
                                <th>Code</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('after_scripts')
<script>
    $(function() {
        var oTable = $('#link-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: '{{ route('admin.link.index') }}'
            },
            columns: [
                {data: 'status', name: 'status'},
                {data: 'email', name: 'email'},
                {data: 'url', name: 'url'},
                {data: 'code', name: 'code'},
            ],
            length: 2
        });
    });
</script>
@endpush