routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')
    ->group(function () {

        Auth::routes();

        Route::namespace('Admin')
            ->middleware(['auth'])
            ->name('admin.')
            ->group(function () {

                // Route Home
                Route::get('home', 'HomeController@index')->name('index');

                // Route Designer
                Route::resource('designer', 'DesignerController');

                // Route Email
                Route::resource('email', 'EmailController');
                Route::get('email/invite/{email}', 'EmailController@invite')->name('email.invite');

                // Route Link
                Route::get('links', 'LinkController@index')->name('link.index');

                // Route User Register
                Route::get('user_register', 'UserRegisterController@index')->name('userRegister.index');
            });
    });

// Register
Route::get('designers/find', 'DesignerController@find')->name('designer.find');
Route::get('register/{url}', 'RegisterInviteController@register')->name('register.invite');
Route::post('register/store/{link}', 'RegisterInviteController@store')->name('register.invite.store');

// Home
Route::get('', 'HomeController@index')->name('index');

app/Models/UserRegister.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserRegister extends Model
{
    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    const GENDER_MALE = 'm';
    const GENDER_FEMALE = 'f';

    public $timestamps = true;
    protected $fillable = ['link_id', 'email', 'name', 'birth_date', 'gender'];

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    public function link()
    {
        return $this->belongsTo(Link::class);
    }

    public function designers()
    {
        return $this->belongsToMany(Designer::class, 'user_register_designers', 'user_register_id', 'designer_id');
    }
    
    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */
    
    /*
    |--------------------------------------------------------------------------
    | ACCESORS
    |--------------------------------------------------------------------------
    */

    public function getGenderLabelAttribute()
    {
        if ($this->gender == self::GENDER_MALE) {
            return "<label class='badge badge-info'>male</label>";
        }
        
        if ($this->gender == self::GENDER_FEMALE) {
            return "<label class='badge badge-danger'>female</label>";
        }
    }

    public function getDesignersLabelAttribute()
    {
        $result = "";
        if ($this->designers()) {
            foreach ($this->designers()->get() as $designer) {
                $result .= "<label class='badge badge-success'>" . $designer->name . "</label> ";
            }
        }

        return $result;
    }
    
    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
}

app/Http/Controllers/Admin/UserRegisterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\UserRegister;
use DataTables;
use Illuminate\Http\Request;

/**
 * Class UserRegisterController
 *
 * @package App\Http\Controllers\Admin
 */
class UserRegisterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = UserRegister::query();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('gender_label', function($row) {
                    return $row->gender_label;
                })
                ->addColumn('designers_label', function($row) {
                    return $row->designers_label;
                })
                ->rawColumns(['gender_label', 'designers_label'])
                ->make(true);
        }
        
        return view('admin.pages.userRegister.index');
    }
}

resources/views/admin/pages/userRegister/index.blade.php
@extends('admin.layouts.template')
@section('pageTitle', 'User Register')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover" id="user-register-table">
                            <thead>
                            <tr>
                                <th>Email</th>
                                <th>Name</th>
                                <th>Birth Date</th>
                                <th>Gender</th>
                                <th>Designers</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('after_scripts')
<script>
    $(function() {
        var oTable = $('#user-register-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: '{{ route('admin.userRegister.index') }}'
            },
            columns: [
                {data: 'email', name: 'email'},
                {data: 'name', name: 'name'},
                {data: 'birth_date', name: 'birth_date'},
                {data: 'gender_label', name: 'gender_label'},
                {data: 'designers_label', name: 'designers_label'},
            ],
            length: 2
        });
    });
</script>
@endpush