routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('admin')
    ->group(function () {

        Auth::routes();

        Route::namespace('Admin')
            ->middleware(['auth'])
            ->name('admin.')
            ->group(function () {

                // Route Home
                Route::get('home', 'HomeController@index')->name('index');

                // Route Designer
                Route::resource('designer', 'DesignerController');

                // Route Email
                Route::resource('email', 'EmailController');
                Route::get('email/invite/{email}', 'EmailController@invite')->name('email.invite');

                // Route Link
                Route::get('links', 'LinkController@index')->name('link.index');

                // Route User Register
                Route::get('user_register', 'UserRegisterController@index')->name('userRegister.index');
            });
    });

// Register
Route::get('designers/find', 'DesignerController@find')->name('designer.find');
Route::get('register/{url}', 'RegisterInviteController@register')->name('register.invite');
Route::post('register/store/{link}', 'RegisterInviteController@store')->name('register.invite.store');

// Home
Route::get('', 'HomeController@index')->name('index');

app/Models/Designer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Designer extends Model
{
    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    public $timestamps = true;
    protected $fillable = ['name'];

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    public function userRegister()
    {
        return $this->belongsToMany(UserRegister::class);
    }
    
    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */
    
    /*
    |--------------------------------------------------------------------------
    | ACCESORS
    |--------------------------------------------------------------------------
    */
    
    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
}

app/Http/Controllers/Admin/DesignerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Traits\FlashMessages;
use App\Http\Requests\DesignerRequest;
use App\Models\Designer;
use DataTables;
use Illuminate\Http\Request;

/**
 * Class DesignerController
 *
 * @package App\Http\Controllers\Admin
 */
class DesignerController extends Controller
{
    use FlashMessages;
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Designer::query();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row) {
                    $editUrl = route('admin.designer.edit', $row->id);
                    $deleteUrl = route('admin.designer.destroy', $row->id);
                    return view('admin.components.action', compact('editUrl', 'deleteUrl', 'row'));
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        
        return view('admin.pages.designer.index');
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.designer.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param \App\Http\Requests\DesignerRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(DesignerRequest $request)
    {
        $designer = Designer::create($request->all());
        if ($designer) {
            $this->flashSuccessStore();
            return redirect()->route('admin.designer.index');
        }
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Designer $designer
     * @return \Illuminate\Http\Response
     */
    public function edit(Designer $designer)
    {
        return view('admin.pages.designer.edit', compact('designer'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\DesignerRequest $request
     * @param \App\Models\Designer $designer
     * @return \Illuminate\Http\Response
     */
    public function update(DesignerRequest $request, Designer $designer)
    {
        $designer = $designer->update($request->all());
        if ($designer) {
            $this->flashSuccessUpdate();
            return redirect()->route('admin.designer.index');
        }
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Designer $designer
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Designer $designer)
    {
        if ($designer->delete()) {
            $this->flashSuccessDelete();
            return redirect()->route('admin.designer.index');
        }
    }
}

app/Http/Controllers/DesignerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Designer;
use Illuminate\Http\Request;

class DesignerController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function find(Request $request)
    {
        $term = trim($request->q);

        if (empty($term)) {
            return \Response::json([]);
        }

        $designers = Designer::where('name', 'like', '%' . $term . '%')->limit(5)->get();

        $formatted_designers = [];

        foreach ($designers as $designer) {
            $formatted_designers[] = ['id' => $designer->id, 'text' => $designer->name];
        }

        return \Response::json($formatted_designers);
    }
}

resources/views/admin/pages/designer/create.blade.php
@extends('admin.layouts.template')
@section('pageTitle', 'Designer')
@section('content')
<div class="row">
    <div class="col-lg-12">
        {{ Form::open(['route' => 'admin.designer.store']) }}
        <div class="card">
            <div class="card-body">
                @include('admin.includes._message')
                <div class="form-group">
                    <label>Name*</label>
                    {!! Form::text('name', null, ["class" => "form-control"]) !!}
                </div>
            </div>
            <div class="card-footer">
                <a href="{{ url()->previous() }}">
                    <button type="button" class="btn btn-primary">
                        <i class="fa fa-arrow-left"></i> Back
                    </button>
                </a>
                <button type="submit" class="btn btn-success">
                    <i class="fa fa-save"></i> Save
                </button>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>
@endsection

resources/views/admin/pages/designer/edit.blade.php
@extends('admin.layouts.template')
@section('pageTitle', 'Designer')
@section('content')
<div class="row">
    <div class="col-lg-12">
        {{ Form::open(['route' => ['admin.designer.update', $designer->id], 'method' => 'PUT']) }}
        <div class="card">
            <div class="card-body">
                @include('admin.includes._message')
                <div class="form-group">
                    <label>Name*</label>
                    {!! Form::text('name', $designer->name, ["class" => "form-control"]) !!}
                </div>
            </div>
            <div class="card-footer">
                <a href="{{ url()->previous() }}">
                    <button type="button" class="btn btn-primary">
                        <i class="fa fa-arrow-left"></i> Back
                    </button>
                </a>
                <button type="submit" class="btn btn-success">
                    <i class="fa fa-save"></i> Update
                </button>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
</div>
@endsection

resources/views/admin/pages/designer/index.blade.php
@extends('admin.layouts.template')
@section('pageTitle', 'Designer')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            @include('admin.includes._alert')
            <div class="card">
                <div class="card-header">
                    <a href="{{ route('admin.designer.create') }}">
                        <button class="btn btn-success">
                            <i class="fa fa-plus"></i> Create
                        </button>
                    </a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover" id="designer-table">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('after_scripts')
<script>
    $(function() {
        var oTable = $('#designer-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: {
                url: '{{ route('admin.designer.index') }}'
            },
            columns: [
                {data: 'name', name: 'name'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ],
            length: 2
        });
    });
</script>
@endpush